#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="train_test_split.py",
        deps=[
            ctx.path_to(ctx, "IN_DATA", "data.pkl"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_DATA", "data_train.pkl"),
            ctx.path_to(ctx, "OUT_DATA", "data_test.pkl"),
        ],
        name="train_test_split",
    )

    ctx(
        features="run_py_script",
        source="feature_importance.py",
        deps=[
            ctx.path_to(ctx, "IN_DATA", "kw_indices.pkl"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_DATA", "sorted_features.csv"),
        ],
        name="feature_importance",
    )
