#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="create_train_test_set.py",
        deps=[
            ctx.path_to(ctx, "IN_DATA", "data.pkl"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_DATA", "variable_reference.csv"),
            ctx.path_to(ctx, "OUT_DATA", "data_train.pkl"),
            ctx.path_to(ctx, "OUT_DATA", "data_test.pkl"),
        ],
        name="create_train_test_set",
    )
