#! python


def build(ctx):

    # select simulation models for which we run the analysis
    import json
    with open("src/models_to_run.json") as handle:
        models_to_run = json.loads(handle.read())["models"]

    for model in models_to_run:
        ctx(
            features="run_py_script",
            source="create_model_specs.py",
            target=ctx.path_to(ctx, "OUT_MODEL_SPECS", "specifications.pkl"),
            name="create_model_specs",
            append=model,
        )
