name: surrogate
channels:
  - defaults
  - conda-forge
  - pytask

dependencies:
  - python=3.7

  - ipykernel=5.1.3
  - jupyterlab=1.1.4
  - nb_conda_kernels=2.2.2

  - pandas=0.25.1
  - numpy

  - scikit-learn
  - keras
  - catboost

  - matplotlib
  - seaborn

  - pytest
  - pytask
  - pylint
  - click
  - black
  - flake8
  - tqdm
  - cloudpickle

  - pip=19.2.3
  - pip:
    - pre-commit==1.18.3


