name: surrogate

channels:
  - defaults
  - conda-forge
  - pytask

dependencies:
  - python=3.8
  - pip
  - conda-build

  - ipykernel
  - jupyterlab
  - nb_conda_kernels

  - pandas
  - numpy

  - scikit-learn
  - keras
  - catboost

  - matplotlib
  - seaborn

  - pytest
  - pytask
  - pylint
  - click
  - cloudpickle

  - black
  - flake8
  - tqdm

  - pip:
    - pre-commit
