name: surrogate

channels:
  - defaults
  - conda-forge
  - pytask

dependencies:
  - python=3.8
  - conda-build

  - ipykernel
  - jupyterlab
  - nb_conda_kernels

  - pandas
  - numpy

  - scikit-learn
  - catboost

  - pytest
  - pytask
  - cloudpickle

  - black
  - flake8

  - pip
  - pip:
    - keras
    - tensorflow
    - pre-commit
