name: surrogate

channels:
  - defaults
  - conda-forge
  - pytask

dependencies:
  - python=3.7
  - conda-build

  - ipykernel=5.1.3
  - jupyterlab=1.1.4
  - nb_conda_kernels=2.2.2

  - pandas=0.25.1
  - numpy=1.19.1

  - scikit-learn=0.23.2
  - keras=2.4.3
  - catboost=0.24

  - matplotlib=3.2.2
  - seaborn=0.10.1

  - pytest=5.2.0
  - pytask=0.0.9
  - pylint=2.6.0
  - click=7.1.2
  - cloudpickle=1.6.0

  - black
  - flake8
  - tqdm

  - pip=19.2.3
  - pip:
    - pre-commit==1.18.3
