#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="create_model_specs.py",
        target=[
            ctx.path_to(ctx, "OUT_MODEL_SPECS", "model_specs.json"),
        ],
        name="create_model_specs",
    )
