#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="assemble_predictions.py",
        deps=[
            ctx.path_to(ctx, "OUT_DATA", "data_test.pkl"),
            ctx.path_to(ctx, "OUT_ANALYSIS", "predictions.pkl"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_FINAL", "data_with_predictions.pkl"),
        ],
        name="assemble_predictions",
    )

    ctx(
        features="run_py_script",
        source="move_to_cloud.py",
        deps=[
            ctx.path_to(ctx, "IN_FINAL", "assemble_predictions.py"),
            ctx.path_to(ctx, "OUT_FINAL", "data_with_predictions.pkl"),
        ],
        name="assemble_predictions",
    )

    ctx(
        features="run_py_script",
        source="bootstrap_plot.py",
        deps=[
            ctx.path_to(ctx, "OUT_ANALYSIS", "bootstrap_mae.csv"),
            ctx.path_to(ctx, "IN_ANALYSIS", "bootstrap.py"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_FIGURES", "bootstrap_mae.pdf")
        ],
        name="boostrap_plot",
    )

    ctx(
        features="run_py_script",
        source="ridge_variable_selection.py",
        deps=[
            ctx.path_to(ctx, "OUT_DATA", "data_train.pkl"),
            ctx.path_to(ctx, "OUT_DATA", "data_test.pkl"),
            ctx.path_to(ctx, "IN_MODEL_CODE", "ridgeregression.py"),
            ctx.path_to(ctx, "IN_MODEL_CODE", "polynomialregression.py"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_FIGURES", "ridge_variable_selection.pdf")
        ],
        name="ridge_variable_selection",
    )

    from src.final.project_dependency_graph import make_project_dependency_graph

    ctx.add_post_fun(make_project_dependency_graph)
