#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="assemble_predictions.py",
        deps=[
            ctx.path_to(ctx, "OUT_DATA", "data_test.pkl"),
            ctx.path_to(ctx, "OUT_DATA", "predictions.pkl"),
        ],
        target=[
            ctx.path_to(ctx, "OUT_DATA", "data_with_predictions.pkl"),
        ],
        name="assemble_predictions",
    )

    ctx(
        features="run_py_script",
        source="move_to_cloud.py",
        deps=[
            ctx.path_to(ctx, "IN_FINAL", "assemble_predictions.py"),
            ctx.path_to(ctx, "OUT_DATA", "data_with_predictions.pkl"),
        ],
        name="assemble_predictions",
    )

    # ctx(
    #     features="run_py_script",
    #     source="bootstrap_plot.py",
    #     deps=[
    #         ctx.path_to(ctx, "OUT_DATA", "bootstrap_mae.csv")
    #     ],
    #     target=[
    #         ctx.path_to(ctx, "OUT_FIGURES", "bootstrap_mae.pdf")
    #     ],
    #     name="boostrap_plot",
    # )

    from src.final.project_dependency_graph import make_project_dependency_graph

    ctx.add_post_fun(make_project_dependency_graph)
