#! python
"""
TODO: Check filetypes of saved models. (line 20)
"""

from src.auxiliary.auxiliary import load_implemented_models


def build(ctx):

    models = load_implemented_models()

    # fit
    ctx(
        features="run_py_script",
        source="fit.py",
        deps=ctx.path_to(ctx, "OUT_DATA", "data_train.pkl"),
        target=[
            ctx.path_to(ctx, "OUT_ANALYSIS", model + ".csv") for model in models
        ],
        name="fit",
    )

    # predict
    ctx(
        features="run_py_script",
        source="predict.py",
        deps=[ctx.path_to(ctx, "OUT_DATA", "data_test.pkl")] + [
            ctx.path_to(ctx, "OUT_ANALYSIS", model + ".csv") for model in models
        ],
        target=[
            ctx.path_to(ctx, "OUT_DATA", "predictions.pkl"),
        ],
        name="predict",
    )

    # evaluate
    ctx(
        features="run_py_script",
        source="evaluate.py",
        deps=ctx.path_to(ctx, "OUT_DATA", "predictions.pkl"),
        target=[
            ctx.path_to(ctx, "OUT_DATA", "losses.csv"),
        ],
        name="evaluate",
    )
